server: "mobile-hub.lambdatest.com"
user: "shubhamr"
key: ""


common_caps:

  "build": "br-1"
  

browser_caps:
  -
    "isRealMobile": "true"
    "platform": "android"
    "deviceName": "Galaxy S21 5G"
    "platformVersion": "11"
    "app": "lt://APP10160621161658231269038249"
